### PR TITLE
Migrate navigation modules from Domain

### PR DESCRIPTION
**Pull request by felipecalvo**
This PR welcomes some navigation modules which were previously on mumuki-domain.

Domain, on its part, loses them in its own PR: https://github.com/mumuki/mumuki-domain/pull/70

### CODE REVIEW

**Comment by flbulgarelli** [comment]
Awesome!

Aren't there any tests to migrate from laboratory to here?

**Comment by felipecalvo** [comment]
There are no tests and:

- it can't be tested here, in flow, since it depends on many external methods from Domain, which would have to be mocked
- it shouldn't be tested in domain, since it's code from a dependency

we're :thought_balloon: recalculating :thought_balloon: what'd be better: maybe doing a more effective model / navigation separation, so the navigation depends less on the domain objects

**Comment by luchotc** [comment]
Nice!

Regarding the tests, we should do both. In domain / laboratory we are testing more general navigation things which uses these modules and it's ok. But here we should implement tests for at least the firm of a _navigation object_ so we can develop this one separately and be sure we are not breaking anything.
We could define which tests are worth adding here together :smile:

**Comment by felipecalvo** [comment]
Alright, so I created a small hierarchy to test on. It's comprised of:

- A root navigable, which includes `TerminalNavigation`
- A leaf navigable, which includes both `ParentNavigation` and `SiblingsNavigation` 

There's also a subroot navigable for hierarchical purposes, which only includes `ParentNavigation`.

Untitled Diagram

image

How does this differ from our domain classes? Terminal classes, such as `exam` and `complement`, only implement `TerminalNavigation` - makes sense since they don't have a parent or siblings. (I'm testing that case). On the other hand, `exercise` and `lesson` implement both `Parent` and `SiblingsNavigation`, because they're highly correlated. (I'm also testing that).

The only outlier I'm not testing is `chapter`, which implements both `Terminal` and `Siblings`. That does not make much sense structurally or at all... for example, `Terminal` says `structural_parent` should be `nil`, yet `Siblings` requires it - and uses it to calculate stuff. I suspect there are a couple of things that work just because they're in the right order. Another example: *both* `Parent` and `Siblings` implement `navigable_name`, yet they're (almost) always used together. `lesson` includes them in one order and `exercise` in another one, hence why each one's name looks right. Not very fond of how this works... I'll use these tests as a starting point and see if I can make it clearer, or in the worst case, we now have tests we didn't before.

**Review by luchotc — APPROVED** [review]
Nice! :tada: 
I totally agree with your comments.
We could integrate this one and leave the improvements in a separate one, right?

**Comment by felipecalvo** [comment]
That's my intention.

**Pull request merged**
